### ISSUE TITLE
[Unstable] jitURLScheme

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/SideStore#385]
### Describe

We want to have the ability for app developers to automatically activate jit so that it’s a seamless process to use jit/debug based apps. Url scheme sidestore://sidejit-enable?bid=BUNDLEIDHERE What ProcessID should be.
sidestore://sidejit-enable?pid=PID

### ToDo

- [X] Add Url scheme to debug bundleid
- [ ] Make Activation more reliable from external apps. (Seems to not work when trying to wake app on first try which we want to immediately activate when first wake).
- [X] Add option in sidestore url scheme to use process Id instead of bundleid.
- [X] Maybe add a screen to tell its attempting to activate
- [X] Have error messages popup if there is any
