### ISSUE TITLE
[Unstable Feature] SwiftUI

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/SideStore#386]
### ToDo
- [ ] Many features are still missing from the app
- [ ] App ratings are shown when no ratings are available
- [ ] Remaining days until the app has to be refreshed are `floor`ed instead of `ceil`ed
- [ ] "Refresh All" in My Apps does not work
- [x] ~App ID list UI issues~
- [x] ~App crashes when opening the list of App IDs when not signed in~
- [x] ~Trusted Sources are missing from the list of sources~
- [x] ~Credits links push an SFSafariView instead of presenting it modally~
- [X] ~Fix output not being displayed in Xcode/idevicedebug run~
- [X] Fix UI being shoved into sidebar on iPad
- [X] Fix 2fa code not being displayed
- [X]  Add app icon switcher and alternative icons
- [ ] Add HMR/code injection (setup: https://github.com/krzysztofzablocki/Inject#individual-developer-setup-once-per-machine)
- [X] Fix 1 trusted source crashing all trusted sources
- [X] Disable ratings
- [X] Add developer mode
- [X] Add advanced settings in-app
